checkpoint_dir: checkpoints/test_run
log_dir: logs/test_run

flops_counter_mode: SILENT
flops_budget: 1.0e20
run_name: ""

optimizer_params:
  lr: 0.1
  momentum: ${general.momentum}
  weight_decay: 5e-4

scheduler_params:
  T_max: ${general.max_epochs}

student: null
teachers_mapping: null
kd_loss: null
